import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

import type { DiscoveredModule, SurfaceRuntime } from './discover'
import { BRAIN_PACKAGES, NEVER_BUNDLE } from './brain'

export type ModuleManifest = {
	generatedAt: string
	generator: 'scripts/codegen'
	brain: Array<{
		exportKey: string
		entryKey: string
		source: string
		runtime: SurfaceRuntime
		nodeFormats: NodeFormat[]
	}>
	modules: Array<{
		key: string
		lane: string
		entry: string
		entryKey: string
		exportNames: string[]
		runtime: SurfaceRuntime
		nodeFormats: NodeFormat[]
		moduleId?: string
		moduleIdSource?: string
		/**
		 * Package-relative SVG path (e.g. `logos/amazon.svg`).
		 * Many packs share one file via `logos/pack-logos.json`.
		 */
		logo?: string
	}>
}

export type NodeFormat = 'esm' | 'cjs'

const NODE_FORMAT_OVERRIDES: Readonly<Partial<Record<string, readonly NodeFormat[]>>> = {
	// @office-open/core currently contains top-level await and cannot be bundled as Node CommonJS.
	presentation: ['esm']
}

function nodeFormatsFor(exportKey: string, runtime: SurfaceRuntime): NodeFormat[] {
	if (runtime === 'edge') return []
	return [...(NODE_FORMAT_OVERRIDES[exportKey] ?? ['esm', 'cjs'])]
}

function exportEntry(typesPath: string, defaultPath: string): string {
	return `{
			"types": "${typesPath}",
			"default": "${defaultPath}"
		}`
}

/** Build package.json "exports" object value text for brain + modules. */
export function renderPackageExports(modules: readonly DiscoveredModule[]): Record<string, unknown> {
	const exports: Record<string, unknown> = {}

	for (const brain of BRAIN_PACKAGES) {
		exports[`./${brain.exportKey}`] = {
			types: `./dist/${brain.entryKey}.d.ts`,
			default: `./dist/${brain.entryKey}.js`
		}
	}

	for (const mod of modules) {
		exports[`./${mod.key}`] = {
			types: `./dist/${mod.entryKey}.d.ts`,
			default: `./dist/${mod.entryKey}.js`
		}
	}

	// Static pack logos (unique SVGs + pack-logos.json alias map).
	exports['./logos/*'] = './logos/*'
	exports['./logos/pack-logos.json'] = './logos/pack-logos.json'

	return exports
}

export function renderTsdownConfig(modules: readonly DiscoveredModule[]): string {
	const entryLines: string[] = []

	for (const brain of BRAIN_PACKAGES) {
		entryLines.push(`\t\t'${brain.entryKey}': '${brain.source}'`)
	}
	for (const mod of modules) {
		entryLines.push(`\t\t'${mod.entryKey}': '${mod.entryRelative}'`)
	}

	const neverBundle = NEVER_BUNDLE.map((d) => `\t\t'${d}'`).join(',\n')

	return `// AUTO-GENERATED by \`bun run codegen\`. Do not edit by hand.
import { defineConfig } from 'tsdown'

export default defineConfig({
	entry: {
${entryLines.join(',\n')}
	},
	format: ['esm'],
	// package.json is "type": "module" — emit .js / .d.ts (not .mjs / .d.mts)
	fixedExtension: false,
	dts: true,
	sourcemap: true,
	deps: {
		neverBundle: [
${neverBundle}
		]
	}
})
`
}

/**
 * `logos/pack-logos.json` maps pack key → logo id (basename without `.svg`).
 * One SVG file is reused by many packs (e.g. amazon → s3, sqs, bedrock, …).
 */
function loadPackLogoMap(repoRoot: string): Record<string, string> {
	const mapPath = path.join(repoRoot, 'logos/pack-logos.json')
	if (!existsSync(mapPath)) return {}
	const raw: unknown = JSON.parse(readFileSync(mapPath, 'utf8'))
	if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) return {}
	const out: Record<string, string> = {}
	for (const [key, value] of Object.entries(raw)) {
		if (typeof value === 'string' && value.length > 0) out[key] = value
	}
	return out
}

function logoPathFor(key: string, packMap: Record<string, string>, repoRoot: string): string | undefined {
	const id = packMap[key] ?? key
	const relative = `logos/${id}.svg`
	if (!existsSync(path.join(repoRoot, relative))) return undefined
	return relative
}

export function renderModuleManifest(
	modules: readonly DiscoveredModule[],
	options: { repoRoot?: string } = {}
): ModuleManifest {
	const repoRoot = options.repoRoot ?? process.cwd()
	const packMap = loadPackLogoMap(repoRoot)
	return {
		generatedAt: new Date().toISOString(),
		generator: 'scripts/codegen',
		brain: BRAIN_PACKAGES.map((b) => ({
			exportKey: b.exportKey,
			entryKey: b.entryKey,
			source: b.source,
			runtime: b.runtime,
			nodeFormats: nodeFormatsFor(b.exportKey, b.runtime)
		})),
		modules: modules.map((m) => {
			const logo = logoPathFor(m.key, packMap, repoRoot)
			return {
				key: m.key,
				lane: m.lane,
				entry: m.entryRelative,
				entryKey: m.entryKey,
				exportNames: m.exportNames,
				runtime: m.runtime,
				nodeFormats: nodeFormatsFor(m.key, m.runtime),
				...(m.moduleId === undefined ? {} : { moduleId: m.moduleId }),
				...(m.moduleIdSource === undefined ? {} : { moduleIdSource: m.moduleIdSource }),
				...(logo === undefined ? {} : { logo })
			}
		})
	}
}

export function renderGeneratedModulesTs(modules: readonly DiscoveredModule[]): string {
	const keys = modules.map((m) => `\t'${m.key}'`).join(',\n')
	const seamKeys = modules
		.filter((m) => m.lane === 'modules')
		.map((m) => `\t'${m.key}'`)
		.join(',\n')
	return `// AUTO-GENERATED by \`bun run codegen\`. Do not edit by hand.
/** Flat public export keys under src/{modules,vendors}. */
export const moduleKeys = [
${keys}
] as const

export type ModuleKey = (typeof moduleKeys)[number]

/** Capability seams under src/modules (brand-neutral model copy). */
export const moduleSeamKeys = [
${seamKeys}
] as const

export type ModuleSeamKey = (typeof moduleSeamKeys)[number]
`
}

/**
 * Inline SVG strings for `defineModule` → `module.logo`.
 * Dedupes by logo id (one SVG, many pack keys via pack-logos.json).
 */
export function renderPackLogosTs(repoRoot: string, modules: readonly DiscoveredModule[]): string {
	const packMap = loadPackLogoMap(repoRoot)
	const uniqueIds = new Map<string, string>() // logoId → svg source

	for (const mod of modules) {
		const logoId = packMap[mod.key] ?? mod.key
		if (uniqueIds.has(logoId)) continue
		const filePath = path.join(repoRoot, 'logos', `${logoId}.svg`)
		if (!existsSync(filePath)) continue
		uniqueIds.set(logoId, readFileSync(filePath, 'utf8').trim())
	}

	const constLines: string[] = []
	const logoIdToConst = new Map<string, string>()
	let i = 0
	for (const [logoId, svg] of [...uniqueIds.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
		const constName = `svg_${logoId.replace(/[^a-zA-Z0-9]+/g, '_')}`
		logoIdToConst.set(logoId, constName)
		constLines.push(`const ${constName} = ${JSON.stringify(svg)}`)
		i += 1
	}
	void i

	const entryLines: string[] = []
	for (const mod of modules) {
		const logoId = packMap[mod.key] ?? mod.key
		const constName = logoIdToConst.get(logoId)
		if (!constName) continue
		// Module id is the defineModule id (same as pack key for all packs).
		entryLines.push(`\t${JSON.stringify(mod.key)}: ${constName}`)
		if (mod.moduleId !== undefined && mod.moduleId !== mod.key) {
			entryLines.push(`\t${JSON.stringify(mod.moduleId)}: ${constName}`)
		}
	}

	return `// AUTO-GENERATED by \`bun run codegen\`. Do not edit by hand.
// Source: logos/*.svg + logos/pack-logos.json — hosts use module.logo from defineModule.

${constLines.join('\n')}

/** Inline SVG by module / pack id (shared files referenced many times). */
export const packLogosByModuleId: Readonly<Record<string, string>> = {
${entryLines.join(',\n')}
}

export function logoForModuleId(id: string): string | undefined {
	return packLogosByModuleId[id]
}
`
}

// silence unused helper in case of future string building
void exportEntry
