import type { DiscoveredModule, SurfaceRuntime } from './discover'
import { BRAIN_PACKAGES, NEVER_BUNDLE } from './brain'

export type ModuleManifest = {
	generatedAt: string
	generator: 'scripts/codegen'
	brain: Array<{
		exportKey: string
		entryKey: string
		source: string
		runtime: SurfaceRuntime
		nodeFormats: NodeFormat[]
	}>
	modules: Array<{
		key: string
		lane: string
		entry: string
		entryKey: string
		exportNames: string[]
		runtime: SurfaceRuntime
		nodeFormats: NodeFormat[]
		moduleId?: string
		moduleIdSource?: string
	}>
}

export type NodeFormat = 'esm' | 'cjs'

const NODE_FORMAT_OVERRIDES: Readonly<Partial<Record<string, readonly NodeFormat[]>>> = {
	// @office-open/core currently contains top-level await and cannot be bundled as Node CommonJS.
	presentation: ['esm']
}

function nodeFormatsFor(exportKey: string, runtime: SurfaceRuntime): NodeFormat[] {
	if (runtime === 'edge') return []
	return [...(NODE_FORMAT_OVERRIDES[exportKey] ?? ['esm', 'cjs'])]
}

function exportEntry(typesPath: string, defaultPath: string): string {
	return `{
			"types": "${typesPath}",
			"default": "${defaultPath}"
		}`
}

/** Build package.json "exports" object value text for brain + modules. */
export function renderPackageExports(modules: readonly DiscoveredModule[]): Record<string, unknown> {
	const exports: Record<string, unknown> = {}

	for (const brain of BRAIN_PACKAGES) {
		exports[`./${brain.exportKey}`] = {
			types: `./dist/${brain.entryKey}.d.ts`,
			default: `./dist/${brain.entryKey}.js`
		}
	}

	for (const mod of modules) {
		exports[`./${mod.key}`] = {
			types: `./dist/${mod.entryKey}.d.ts`,
			default: `./dist/${mod.entryKey}.js`
		}
	}

	return exports
}

export function renderTsdownConfig(modules: readonly DiscoveredModule[]): string {
	const entryLines: string[] = []

	for (const brain of BRAIN_PACKAGES) {
		entryLines.push(`\t\t'${brain.entryKey}': '${brain.source}'`)
	}
	for (const mod of modules) {
		entryLines.push(`\t\t'${mod.entryKey}': '${mod.entryRelative}'`)
	}

	const neverBundle = NEVER_BUNDLE.map((d) => `\t\t'${d}'`).join(',\n')

	return `// AUTO-GENERATED by \`bun run codegen\`. Do not edit by hand.
import { defineConfig } from 'tsdown'

export default defineConfig({
	entry: {
${entryLines.join(',\n')}
	},
	format: ['esm'],
	// package.json is "type": "module" — emit .js / .d.ts (not .mjs / .d.mts)
	fixedExtension: false,
	dts: true,
	sourcemap: true,
	deps: {
		neverBundle: [
${neverBundle}
		]
	}
})
`
}

export function renderModuleManifest(modules: readonly DiscoveredModule[]): ModuleManifest {
	return {
		generatedAt: new Date().toISOString(),
		generator: 'scripts/codegen',
		brain: BRAIN_PACKAGES.map((b) => ({
			exportKey: b.exportKey,
			entryKey: b.entryKey,
			source: b.source,
			runtime: b.runtime,
			nodeFormats: nodeFormatsFor(b.exportKey, b.runtime)
		})),
		modules: modules.map((m) => ({
			key: m.key,
			lane: m.lane,
			entry: m.entryRelative,
			entryKey: m.entryKey,
			exportNames: m.exportNames,
			runtime: m.runtime,
			nodeFormats: nodeFormatsFor(m.key, m.runtime),
			...(m.moduleId === undefined ? {} : { moduleId: m.moduleId }),
			...(m.moduleIdSource === undefined ? {} : { moduleIdSource: m.moduleIdSource })
		}))
	}
}

export function renderGeneratedModulesTs(modules: readonly DiscoveredModule[]): string {
	const keys = modules.map((m) => `\t'${m.key}'`).join(',\n')
	const seamKeys = modules
		.filter((m) => m.lane === 'modules')
		.map((m) => `\t'${m.key}'`)
		.join(',\n')
	return `// AUTO-GENERATED by \`bun run codegen\`. Do not edit by hand.
/** Flat public export keys under src/{modules,vendors}. */
export const moduleKeys = [
${keys}
] as const

export type ModuleKey = (typeof moduleKeys)[number]

/** Capability seams under src/modules (brand-neutral model copy). */
export const moduleSeamKeys = [
${seamKeys}
] as const

export type ModuleSeamKey = (typeof moduleSeamKeys)[number]
`
}

// silence unused helper in case of future string building
void exportEntry
